use tempdb
go
  
CHECKPOINT;
GO
  
DBCC DROPCLEANBUFFERS;
GO
  
DBCC FREEPROCCACHE;
GO
  
DBCC FREESYSTEMCACHE('ALL')
GO
  
DBCC SHRINKFILE (tempdev,1)
DBCC SHRINKFILE (templog,1)
DBCC SHRINKFILE (temp2,1)
DBCC SHRINKFILE (temp3,1)
DBCC SHRINKFILE (temp4,1)
DBCC SHRINKFILE (temp5,1)
DBCC SHRINKFILE (temp6,1)
DBCC SHRINKFILE (temp7,1)
DBCC SHRINKFILE (temp8,1)
