USE teste /*BANCO QUE EU QUERO VISUALIZAR AS TABELAS, COLUNAS, ENTRE OUTROS DADOS*/

IF OBJECT_ID ('TEMPDB..#SYS') IS NOT NULL
DROP TABLE #SYS
IF OBJECT_ID ('TEMPDB..#DADOS_DO_BANCO') IS NOT NULL
DROP TABLE #DADOS_DO_BANCO

CREATE TABLE #SYS (BANCO VARCHAR (100), ESQUEMA VARCHAR(20), TABELA VARCHAR(100), COLUNA VARCHAR(100),TIPO_DA_COLUNA VARCHAR(100)
, TAMANHO_STRING VARCHAR(20), TAMANHO_NUMERO VARCHAR(20), TAMANHO_NUMERO_2 VARCHAR(20),[PERMITE_NULO?] VARCHAR(20), POSICAO_DA_COLUNA INTEGER)
CREATE TABLE #DADOS_DO_BANCO (BANCO VARCHAR (100), ESQUEMA VARCHAR(20), TABELA VARCHAR(100), COLUNA VARCHAR(100),TIPO_DA_COLUNA VARCHAR(100)
, [PERMITE_NULO?] VARCHAR(20), POSICAO_DA_COLUNA INTEGER)

INSERT INTO #SYS
SELECT T.TABLE_CATALOG,T.TABLE_SCHEMA,T.TABLE_NAME,C.COLUMN_NAME, UPPER(DATA_TYPE) AS DATA_TYPE,
CHARACTER_MAXIMUM_LENGTH,NUMERIC_PRECISION,NUMERIC_PRECISION_RADIX,IS_NULLABLE,ORDINAL_POSITION
 FROM INFORMATION_SCHEMA.TABLES T
INNER JOIN  INFORMATION_SCHEMA.COLUMNS C ON C.TABLE_NAME = T.TABLE_NAME
WHERE T.TABLE_NAME NOT IN ('sysdiagrams') and t.TABLE_TYPE in ('BASE TABLE')

UPDATE #SYS
SET TAMANHO_STRING = 'MAX'
WHERE TAMANHO_STRING = '-1'

INSERT INTO #DADOS_DO_BANCO
SELECT BANCO,ESQUEMA AS ESQUEMA, TABELA, COLUNA,
CASE WHEN TAMANHO_STRING IS NULL AND TIPO_DA_COLUNA <> 'DECIMAL' THEN TIPO_DA_COLUNA
     WHEN TAMANHO_STRING IS NOT NULL THEN TIPO_DA_COLUNA+ '('+ TAMANHO_STRING +')'
     WHEN TAMANHO_STRING IS NULL AND TIPO_DA_COLUNA = 'DECIMAL' 
     THEN TIPO_DA_COLUNA + '('+ TAMANHO_NUMERO + ','+TAMANHO_NUMERO_2 +')' END AS TIPO_DA_COLUNA,
CASE WHEN [PERMITE_NULO?] = 'NO' THEN 'NÃO PERMITE NULO'
ELSE 'PERMITE NULO'END [PERMITE_NULO?], POSICAO_DA_COLUNA 
 FROM #SYS 
 
 
 SELECT * FROM #DADOS_DO_BANCO
